name: CI/CD

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main

env:
  SERVICE_NAME: market-analysis-api

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    environment: dev
    steps:
      - uses: actions/checkout@v3
        name: Checkout ${{ github.repository }}
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pipx
      - uses: chartboost/ruff-action@v1  # RUFF requires pipx
      - name: Run tests
        run: |
          python -m pytest --verbose --cov --cov-report=xml
